### ISSUE TITLE
Advanced Search

### ISSUE THREAD

**Issue by datajohnson** [icefoganalytics/yhsi#14]
When searching in Advanced search and adding filters, then you press "Search" button, it filters correctly, but if you collapse the "Advanced search" section, it resets the filters. They should remain set.

**Comment by klondikemarlen** [comment]
Fixed in [:fire: Drop constraint of clearing advanced search when closed.](https://github.com/icefoganalytics/yhsi/commit/53943a0e0cf11d50ca3a77716f5d3da4c1df7fe8).

I accidentally pushed to `test` directly and since it was such a small change I left it as is though a PR would have been better.
